def get_level(xp):
    return xp // 200 + 1

item_emojis = {
    "Ancient Relic": "🏺",
    "Ashes": "🔥",
    "Basic Armour": "🛡️",
    "Bear Claw": "🐻",
    "Creeper Dust": "🌫️",
    "Cracked Fang": "⚔️",
    "Cracked Stone": "🪨",
    "Croak Sac": "🐸",
    "Deer Antler": "🏹",
    "Demon Horn": "👹",
    "Dragon Scale": "🐉",
    "Eldritch Tome": "📜",
    "Explosive Core": "💥",
    "Explosive Powder": "💣",
    "Fire Gland": "🔥",
    "Fragmented Shell": "🐚",
    "Frog Leg": "🐸",
    "Fur Pelt": "🦊",
    "Glowing Core": "🔆",
    "Glowing Eye": "🟩",
    "Golden Apples": "🍏",
    "Heavy Rock": "🏗️",
    "Hoof": "🐴",
    "Hydra Venom": "🐍",
    "Iron Sword": "⚔️⛓️",
    "Legendary Gem": "💠",
    "Life Potion": "🧪",
    "Lizard Scale": "🦎",
    "Lucky Charm": "🍀",
    "Magic Core": "🔮",
    "Mystic Leaf": "🍁",
    "Mystic Orb": "🔮",
    "Phoenix Feather": "🪶",
    "Poison Fang": "🕷️",
    "Reptile Scale": "🦎",
    "Rusty Dagger": "🗡️",
    "Shadow Orb": "⚫",
    "Sharp Claw": "🦅",
    "Sharp Tooth": "🦷",
    "Silk Thread": "🧵",
    "Slime Essence": "🧪",
    "Slime Gel": "🧪",
    "Slippery Skin": "🦎",
    "Small Gem": "💎",
    "Soft Fur": "🧥",
    "Spider Leg": "🕷️",
    "Spider Silk": "🕸️",
    "Steel Armour": "🛡️⛓️",
    "Sticky Gel": "🔵",
    "Sticky Residue": "🟡",
    "Sword": "⚔️",
    "Tattered Hide": "🧥",
    "Titan's Heart": "❤️",
    "Torn Pouch": "🏹",
    "Toxic Slime": "🧪",
    "Venom Blade": "🗡️",
    "Venom Gland": "🧪",
    "Venom Sac": "🕸️",
    "Warrior's Medal": "🎖️",
    "Webbed Arrow": "🏹",
    "Wolf Fang": "🦴",
    "Wooden Sword": "🪵⚔️"
}